language: node_js
node_js:
  - "12.13"
deploy:
  provider: npm
  email: tanjiahui2015@foxmail.com
  api_key:
    secure: KZZQXUg5JvRA3gifI/zO+eoJ3RScOmPl2m6koe+PWtnfqBPawrXwhfivcdv7mlURlZdDyuBD01GOQHa7L2HmUjD8Bued3oNMxayLi+BBRyI2WbMraAQMXfElCFQCvEhsGPCF1v+O36NHZENzFS+2KjdmqPVaLmQ4FDgwHo8qWV8Qm/ZcNx24b3vM70df8ysJtL4CCCvF6LfgcwR2DgFM8GVfCNngfwyWsGVs22dAfJNdiF/VRdawKIocztBAokWPNWK//0o+j371hRCOoYBkmkbr1FyrttBkiUEih+q1DjVz8DNZ2uCNbXGFuDetd27axgGhVcU2kUH3PIclWbH2lsImOI1QjWWfktdu7X5LdHaSuqmfQmUAWqAQv2H0p0LxsnAyk/obXAYUmIyL3zGHswHxRthtJsUaz4mkYmJs6jz3v71ctJBdsjrOBzQaMXHFMcAqX1gL51+ADdPf3bskVopq9KYQp324ucl6ju08IrZHOLLZgLlXIZi1dftYGOcLE+w6Fo6Z8sZdoEOTsAFS4DwC5Ax49K2Gk3Fq2squCQFbjJL++lRcWUbQb65smKwGpDNHtJ9aEyh5iG+F/xVKtVc/rd5SJ7EV8qCOW5xVjNfsYQekUKm1umjxL8K4zh2BkCjnTzwEeBAtxiSkYYcnla3Klbq/BRDYtM1Q4+eiW0o=
  on:
    tags: true
    branch: master
    repo: flytam/babel-plugin-resolve-config-json
