language: node_js
node_js:
  - "12.13"
deploy:
  provider: npm
  email: tanjiahui2015@foxmail.com
  skip_cleanup: true
  api_key:
    secure: G4uSx4V1Fmr/4075odYi9lyuCZSoEMXVJU7kPk4HjzBp/fS7kZvNTEE+5N4MJgDshR+eeVJNLQvAf09SQE1oWkhBTnu4QPSlfD79JFSOSYxtnq15lDtzYOeDnh48gIoyMYM/zfbredkRqifT8anj0eePOjF5nJFkafIQWMWDMt35h2WTleWDQ6Dwx/Uj7lzOei+MSDFZvPZexT/5YkKMlMI2VKs92UklbELpSXbJNXTDktxO5HVX4gVfSLQO/M/9u4ZUJjTyETlVwKgskRafrPZOmI00sbDMzLXhXy2SQNT596Adoqk4pHYb4NbbCmJf55rXHcXzFN7WPZdXEhzNugeo0IG01sPYAR7zdtz/pKs+yDbtyKagryiNaZTnYMgEP8go2GVvxP3k7tkG+bP2zW/zLIwUAhMG2oJySO2qC4lBV1h0UEUBJAtM0vEVuhG0XUcyB4uYexOscz8d6DPJueVBQs/HPghkH1z1B7L5jCNKLpyqEu+fHIxTA/T1jwPfa3x4dhdjzDd9zQRB7RDEWgc1ZvjvT21C3V26nx1QQy96oDVY1ple73/BdGPZbCyd51TjsgLgAo+j6XDRAkHDqG8Ofj/HwU1MgxKZ/JwJplG05YRjmefiD+7+oHTPouYPORdJvfacmLFU4xNNNkwNBki/vBN2Kusff5MNt/rfTK4=
  on:
    tags: true
    branch: master
    repo: flytam/babel-plugin-resolve-config-json
